INSERT INTO dbo.venue 
(vendorId, imgUrl, heading, guests, location, price, description)
VALUES
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','https://www.hiddencitysecrets.com.au/wp-content/uploads/2025/10/Bar-Bambi-Melbourne-Functions-CBD-Rooms-Hire-Venues-Party-Birthday-Friends-Corporate-Events-Cocktails-Dancing-Live-Music-Good-Food-Italian-001.jpg','Bar Bambi',120,'Melbourne CBD',85,'The Restaurant area on the lower level of the venue is available to be cordoned off exclusively for your special occasion from Thursday - Sunday during normal hours of trade.'),

('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','https://www.hiddencitysecrets.com.au/wp-content/uploads/2023/09/Hophaus-venue-hire-melbourne-function-rooms-venues-birthday-party-event-wedding-engagement-corporate-room-small-event-southbank-015.jpg','Hophaus',200,'Southbank',95,'With an expansive art deco-inspired dining hall, including their glazed polychrome brick centrepiece bier bar with 30 draught bier taps and an open rotisserie-fired kitchen, you will quickly agree that Hophaus delivers on its mission to make you and your belly happy with its delicious German & European inspired menu, and warm, contemporary surrounds.'),

('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','https://www.hiddencitysecrets.com.au/wp-content/uploads/2024/06/Moon-Dog-Wild-West-Function-Venues-Melbourne-Venue-Hire-Footscray-Rooms-Fun-Corporate-Event-Team-Building-Birthday-Party-Wedding-Anniversary-Cool-Engagement-1.jpg','Moon Dog Wild West',300,'Docklands',70,'Backed by Moon Dog’s renowned hospitality and flair for bold, exciting venues, Doglands delivers atmosphere and flavour in equal measure. With a flexible floor plan and an experienced team on hand, the space can be tailored to suit everything from casual dining to large-scale celebrations.'),

('dddddddd-dddd-dddd-dddd-dddddddddddd','https://www.hiddencitysecrets.com.au/wp-content/uploads/2016/01/Carlton-Club-Function-Venues-Melbourne-Venue-Hire-CBD-Rooms-Rooftop-Event-Spaces-Birthday-Party-Corporate-Room-Unique-001.jpg','The Carlton Club',350,'Melbourne CBD',120,'The venue spans across multiple levels, each with its own energy and decor. Featuring a range of unique indoor and outdoor function spaces, it’s perfect for intimate booth dinners, rooftop takeovers or club nights for up to 300 guests.'),

('dddddddd-dddd-dddd-dddd-dddddddddddd','https://www.hiddencitysecrets.com.au/wp-content/uploads/2023/06/glasshaus-function-venues-melbourne-venue-hire-cocktail-party-functions-warehouse-rooms-private-room-open-spaces-event-space-corporate-events-small-012.jpg','Glasshaus',180,'Richmond',110,'A bright and modern venue surrounded by parklands, offering floor-to-ceiling windows and natural light.'),

('dddddddd-dddd-dddd-dddd-dddddddddddd','https://www.hiddencitysecrets.com.au/wp-content/uploads/2024/04/death-or-glory-restaurant-restaurants-pub-pubs-diner-eats-food-drinks-prahran-melbourne-14.jpg','Death or Glory',150,'Prahran',95,'Death or Glory is a Bar & Restaurant located in the bustle of Chapel St in Prahran. With a killer menu, trivia and comedy nights and a wide range of food and drink, your whole week is literally sorted.'),

('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee','https://www.hiddencitysecrets.com.au/wp-content/uploads/2024/12/Blossom-Rooftop-Bar-Function-Venues-Melbourne-Venue-Hire-CBD-Rooms-Birthday-Party-City-View-Engagement-Wedding-Corporate-13.jpg','Blossom Rooftop Bar',250,'Melbourne CBD',130,'A rooftop venue with stunning city skyline views and a luxurious contemporary atmosphere.'),

('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee','https://www.hiddencitysecrets.com.au/wp-content/uploads/2024/03/The-Tippler-Co-Restaurant-East-Melbourne-Restaurants-Private-Group-Share-Dinning-Top-Best-Good-Casual-Outdoor-Cool-Tapas-011.jpg','The Tippler & Co',140,'East Melbourne',100,'Located only a stone’s throw from the MCG, The Tippler & Co is a lush plant-filled bar and eatery that has been built on a passion for good hospitality, food and drink.'),

('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee','https://www.hiddencitysecrets.com.au/wp-content/uploads/2025/09/Chiki-Chan-Restaurant-Melbourne-Aisan-Fusion-Mordialloc-Dinner-Drinks-Wine-Bayside-Restaurants-Family-Friends-Good-Food-Live-Music-001.jpg','Chiki Chan',300,'Mordialloc',115,'Chiki Chan brings a fresh twist to Melbourne’s dining scene with a menu that fuses Asian flavours and modern Australian favourites.');